packer {
  required_plugins {
    proxmox = {
      version = ">= 1.1.2"
      source  = "github.com/hashicorp/proxmox"
    }
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
  }
}

locals {
  my_public_key = trimspace(file("~/.ssh/id_rsa.pub"))
}

variable "ssh_password" {
  type      = string
  sensitive = true
  default   = null 
}

variable "env" {
  type        = string
  description = "Passed from bake.sh (e.g., dev or prod)"
}

variable "metadata_path" {
  type        = string
  description = "The local path to the pre-rendered metadata file from the reverse proxy repo."
}

variable "proxmox_vmid" {
  type        = string
  description = "The specific VMID from NetBox inventory. Generated by script"
}

variable "proxmox_api_token_secret" {
  type      = string
  sensitive = true
}

variable "proxmox_api_url" { type = string }

variable "clone_template_name" {
  type    = string
  default = "debian-trixie-packer" 
}

source "proxmox-clone" "jfkhome-base" {
  proxmox_url = var.proxmox_api_url
  vm_id       = var.proxmox_vmid
  username    = "terraform@pam!main_terraform"
  token       = var.proxmox_api_token_secret
  node    = "pve"

  # Template source settings
  clone_vm = var.clone_template_name
  full_clone = true

  # Enable QEMU agent so Packer can query the IP
  qemu_agent = true

  # Target VM settings
  vm_name = "jfkhome-${var.env}-golden"
  pool     = "Template"

  cores  = 4
  memory = 4096

  ssh_username = "kevin"
  ssh_handshake_attempts = 100
  ssh_timeout  = "15m"
  ssh_private_key_file = "~/.ssh/id_rsa"
}

build {
  sources = ["proxmox-clone.jfkhome-base"]

  # 0: Move disk to local-zfs from NAS
  provisioner "shell-local" {
    inline = [
      "ssh root@pve 'qm move_disk ${var.proxmox_vmid} scsi0 local-zfs --delete'"
    ]
  }

  # Run Ansible playbook
  provisioner "ansible" {
    playbook_file = "./_packer-build.yaml"
    user          = "kevin"
    use_proxy     = false
    ansible_env_vars = [
      "ANSIBLE_ROLES_PATH=./roles",
      "ANSIBLE_HOST_KEY_CHECKING=False"
    ]
    # Pass target_app variable
    extra_arguments = [
      "--extra-vars", "target_app=${var.target_app} env=${var.env}"
    ]
  }

  # Upload the pre-rendered metadata file
  provisioner "file" {
    source      = var.metadata_path
    destination = "/tmp/services_meta.json"
  }


  # Move haproxy and keepalived configs to vm template 
  provisioner "shell" {
    inline = [            
      "sudo mv -f /tmp/services_meta.json /var/www/html/services_meta.json",
      "sudo chown www-data:www-data /var/www/html/services_meta.json",
      "sudo chmod 644 /var/www/html/services_meta.json",
      "echo 'Verifying final destination:'"
    ]
  }


  # Final Sanitization 
  provisioner "shell" {
    inline = [
      "sudo cloud-init clean --logs",
      "sudo truncate -s 0 /etc/machine-id",
      "sudo cloud-init clean --logs", 
      "sudo rm -f /etc/netplan/*", 
      "sudo truncate -s 0 /etc/machine-id",
      "sudo sync"
    ]
  }
  
  post-processor "shell-local" {
    inline = [
      # copy the disk from local-zfs to NAS (nfs)
    "ssh root@pve 'qm move_disk ${var.proxmox_vmid} scsi0 truenas-nfs --delete'"    ]
  }
}