dev_host: "{{ (groups['repo_jfkhome'] | intersect(groups['env_dev']) | intersect(groups['role_vm_template']))[0] }}"
vmid: "{{ hostvars[dev_host].custom_fields.vmid }}"
pve_node: "pve"
golden_storage: "truenas-nfs"